import { Inter } from "next/font/google";
import Sidebar from "./Sidebar";
import "./globals.css";
import Footer from "./Footer";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Premier Stay Ventures</title>
      </head>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <div className="flex flex-row flex-grow">
          <Sidebar />
          <main className="flex-grow" style={{ marginLeft: "256px" }}>
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
